In [1]:
import torch
import numpy as np

In [16]:
def generate_class_mask(label, classes):
    label, classes = torch.broadcast_tensors(label,
                                             classes.unsqueeze(1).unsqueeze(2))
    print(classes)
    print(label)
    class_mask = label.eq(classes)
    print(class_mask)
    class_mask = class_mask.sum(0, keepdims=True)
    print(class_mask)
    return class_mask

def get_class_masks(labels, rcm=None):
    class_masks = []
    if rcm != None:
        rcm = torch.tensor(rcm)
    for label in labels:
        classes = torch.unique(labels)
        nclasses = classes.shape[0]
        class_choice = np.random.choice(
            nclasses, int((nclasses + nclasses % 2) / 2), replace=False)
        classes = classes[torch.Tensor(class_choice).long()]
        if rcm != None:
            classes = torch.cat((classes, rcm))
            classes = torch.unique(classes)
        class_masks.append(generate_class_mask(label, classes).unsqueeze(0))
    return class_masks

In [17]:
rcm = [7,8,9]
x = torch.randint(10, (2,1,4,4))
print(x)
y = get_class_masks(x, rcm=rcm)
print(y)

tensor([[[[1, 1, 8, 1],
          [2, 4, 3, 7],
          [5, 2, 6, 5],
          [8, 5, 6, 8]]],


        [[[1, 0, 6, 8],
          [9, 9, 9, 5],
          [2, 8, 4, 7],
          [4, 4, 6, 2]]]])
tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]],

        [[6, 6, 6, 6],
         [6, 6, 6, 6],
         [6, 6, 6, 6],
         [6, 6, 6, 6]],

        [[7, 7, 7, 7],
         [7, 7, 7, 7],
         [7, 7, 7, 7],
         [7, 7, 7, 7]],

        [[8, 8, 8, 8],
         [8, 8, 8, 8],
         [8, 8, 8, 8],
         [8, 8, 8, 8]],

        [[9, 9, 9, 9],
         [9, 9, 9, 9],
         [9, 9, 9, 9],
         [9, 9, 9, 9]]])
tensor([[[ True,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False],
         [False, False, Fa